project:
  type: website


format:
  html:
    backgroundcolor: "#FFFFFF"
    page-layout: full
    toc: true
    code-fold: false
    theme: flatly
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
    mainfont: "Lato"
    code-tools: false
    font-size: 2.2rem;
    minial: true
    twitter-card:
      image: "images/airport.jpg"
    keywords: aviation, sustainability, net-zero, AI, machine learning
    pagetitle: Towards Net-Zero Aviation with AI
    favicon: images/logo.ico


      
website:
  favicon: images/logo.ico
  page-navigation: false